/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      success\n      message\n      user {\n        id\n        email\n        firstName\n        lastName\n        isActive\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation Register(\n    $email: String!\n    $password: String!\n    $firstName: String!\n    $lastName: String!\n    $tenantSlug: String!\n  ) {\n    register(\n      email: $email\n      password: $password\n      firstName: $firstName\n      lastName: $lastName\n      tenantSlug: $tenantSlug\n    ) {\n      success\n      message\n      user {\n        id\n        email\n        firstName\n        lastName\n        isActive\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": typeof types.RegisterDocument,
    "\n  mutation Logout {\n    logout\n  }\n": typeof types.LogoutDocument,
    "\n  mutation CreateMerchProduct($input: CreateMerchProductInput!) {\n    createMerchProduct(input: $input) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateMerchProductDocument,
    "\n  mutation UpdateMerchProduct($id: ID!, $input: UpdateMerchProductInput!) {\n    updateMerchProduct(id: $id, input: $input) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateMerchProductDocument,
    "\n  mutation DeleteMerchProduct($id: ID!) {\n    deleteMerchProduct(id: $id)\n  }\n": typeof types.DeleteMerchProductDocument,
    "\n  mutation CreateMerchCategory($input: CreateMerchCategoryInput!) {\n    createMerchCategory(input: $input) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateMerchCategoryDocument,
    "\n  mutation UpdateMerchCategory($id: ID!, $input: UpdateMerchCategoryInput!) {\n    updateMerchCategory(id: $id, input: $input) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateMerchCategoryDocument,
    "\n  mutation DeleteMerchCategory($id: ID!) {\n    deleteMerchCategory(id: $id)\n  }\n": typeof types.DeleteMerchCategoryDocument,
    "\n  mutation CreatePresignedUploadUrl($fileType: String!) {\n    createPresignedUploadUrl(fileType: $fileType) {\n      uploadUrl\n      fileUrl\n    }\n  }\n": typeof types.CreatePresignedUploadUrlDocument,
    "\n  mutation CreateNewsArticle($input: CreateNewsArticleInput!) {\n    createNewsArticle(input: $input) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateNewsArticleDocument,
    "\n  mutation UpdateNewsArticle($id: ID!, $input: UpdateNewsArticleInput!) {\n    updateNewsArticle(id: $id, input: $input) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateNewsArticleDocument,
    "\n  mutation DeleteNewsArticle($id: ID!) {\n    deleteNewsArticle(id: $id)\n  }\n": typeof types.DeleteNewsArticleDocument,
    "\n  mutation CreateNewsCategory($input: CreateNewsCategoryInput!) {\n    createNewsCategory(input: $input) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateNewsCategoryDocument,
    "\n  mutation UpdateNewsCategory($id: ID!, $input: UpdateNewsCategoryInput!) {\n    updateNewsCategory(id: $id, input: $input) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateNewsCategoryDocument,
    "\n  mutation DeleteNewsCategory($id: ID!) {\n    deleteNewsCategory(id: $id)\n  }\n": typeof types.DeleteNewsCategoryDocument,
    "\n  mutation CreateTenant($input: CreateTenantInput!) {\n    createTenant(input: $input) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateTenantDocument,
    "\n  mutation UpdateTenant($id: ID!, $input: UpdateTenantInput!) {\n    updateTenant(id: $id, input: $input) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateTenantDocument,
    "\n  mutation DeleteTenant($id: ID!) {\n    deleteTenant(id: $id)\n  }\n": typeof types.DeleteTenantDocument,
    "\n  query GetMe {\n    me {\n      id\n      email\n      firstName\n      lastName\n      isActive\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetMeDocument,
    "\n  query GetMerchProducts(\n    $language: String\n    $status: String\n    $categoryId: ID\n    $isFeatured: Boolean\n    $limit: Int\n    $offset: Int\n  ) {\n    merchProducts(\n      language: $language\n      status: $status\n      categoryId: $categoryId\n      isFeatured: $isFeatured\n      limit: $limit\n      offset: $offset\n    ) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetMerchProductsDocument,
    "\n  query GetMerchProductById($id: ID!, $language: String) {\n    merchProductById(id: $id, language: $language) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetMerchProductByIdDocument,
    "\n  query GetMerchCategories($language: String) {\n    merchCategories(language: $language) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetMerchCategoriesDocument,
    "\n  query GetMerchCategoryById($id: ID!, $language: String) {\n    merchCategoryById(id: $id, language: $language) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetMerchCategoryByIdDocument,
    "\n  query GetNewsArticles(\n    $language: String\n    $status: String\n    $priority: String\n    $categoryId: ID\n    $limit: Int\n    $offset: Int\n  ) {\n    newsArticles(\n      language: $language\n      status: $status\n      priority: $priority\n      categoryId: $categoryId\n      limit: $limit\n      offset: $offset\n    ) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetNewsArticlesDocument,
    "\n  query GetNewsArticleById($id: ID!, $language: String) {\n    newsArticleById(id: $id, language: $language) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetNewsArticleByIdDocument,
    "\n  query GetNewsCategories($language: String) {\n    newsCategories(language: $language) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetNewsCategoriesDocument,
    "\n  query GetNewsCategoryById($id: ID!, $language: String) {\n    newsCategoryById(id: $id, language: $language) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetNewsCategoryByIdDocument,
    "\n  query GetTenants {\n    tenants {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetTenantsDocument,
    "\n  query GetTenantById($id: ID!) {\n    tenantById(id: $id) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetTenantByIdDocument,
    "\n  query GetTenantBySlug($slug: String!) {\n    tenantBySlug(slug: $slug) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetTenantBySlugDocument,
};
const documents: Documents = {
    "\n  mutation Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      success\n      message\n      user {\n        id\n        email\n        firstName\n        lastName\n        isActive\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.LoginDocument,
    "\n  mutation Register(\n    $email: String!\n    $password: String!\n    $firstName: String!\n    $lastName: String!\n    $tenantSlug: String!\n  ) {\n    register(\n      email: $email\n      password: $password\n      firstName: $firstName\n      lastName: $lastName\n      tenantSlug: $tenantSlug\n    ) {\n      success\n      message\n      user {\n        id\n        email\n        firstName\n        lastName\n        isActive\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.RegisterDocument,
    "\n  mutation Logout {\n    logout\n  }\n": types.LogoutDocument,
    "\n  mutation CreateMerchProduct($input: CreateMerchProductInput!) {\n    createMerchProduct(input: $input) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateMerchProductDocument,
    "\n  mutation UpdateMerchProduct($id: ID!, $input: UpdateMerchProductInput!) {\n    updateMerchProduct(id: $id, input: $input) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateMerchProductDocument,
    "\n  mutation DeleteMerchProduct($id: ID!) {\n    deleteMerchProduct(id: $id)\n  }\n": types.DeleteMerchProductDocument,
    "\n  mutation CreateMerchCategory($input: CreateMerchCategoryInput!) {\n    createMerchCategory(input: $input) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateMerchCategoryDocument,
    "\n  mutation UpdateMerchCategory($id: ID!, $input: UpdateMerchCategoryInput!) {\n    updateMerchCategory(id: $id, input: $input) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateMerchCategoryDocument,
    "\n  mutation DeleteMerchCategory($id: ID!) {\n    deleteMerchCategory(id: $id)\n  }\n": types.DeleteMerchCategoryDocument,
    "\n  mutation CreatePresignedUploadUrl($fileType: String!) {\n    createPresignedUploadUrl(fileType: $fileType) {\n      uploadUrl\n      fileUrl\n    }\n  }\n": types.CreatePresignedUploadUrlDocument,
    "\n  mutation CreateNewsArticle($input: CreateNewsArticleInput!) {\n    createNewsArticle(input: $input) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateNewsArticleDocument,
    "\n  mutation UpdateNewsArticle($id: ID!, $input: UpdateNewsArticleInput!) {\n    updateNewsArticle(id: $id, input: $input) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateNewsArticleDocument,
    "\n  mutation DeleteNewsArticle($id: ID!) {\n    deleteNewsArticle(id: $id)\n  }\n": types.DeleteNewsArticleDocument,
    "\n  mutation CreateNewsCategory($input: CreateNewsCategoryInput!) {\n    createNewsCategory(input: $input) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateNewsCategoryDocument,
    "\n  mutation UpdateNewsCategory($id: ID!, $input: UpdateNewsCategoryInput!) {\n    updateNewsCategory(id: $id, input: $input) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateNewsCategoryDocument,
    "\n  mutation DeleteNewsCategory($id: ID!) {\n    deleteNewsCategory(id: $id)\n  }\n": types.DeleteNewsCategoryDocument,
    "\n  mutation CreateTenant($input: CreateTenantInput!) {\n    createTenant(input: $input) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateTenantDocument,
    "\n  mutation UpdateTenant($id: ID!, $input: UpdateTenantInput!) {\n    updateTenant(id: $id, input: $input) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateTenantDocument,
    "\n  mutation DeleteTenant($id: ID!) {\n    deleteTenant(id: $id)\n  }\n": types.DeleteTenantDocument,
    "\n  query GetMe {\n    me {\n      id\n      email\n      firstName\n      lastName\n      isActive\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetMeDocument,
    "\n  query GetMerchProducts(\n    $language: String\n    $status: String\n    $categoryId: ID\n    $isFeatured: Boolean\n    $limit: Int\n    $offset: Int\n  ) {\n    merchProducts(\n      language: $language\n      status: $status\n      categoryId: $categoryId\n      isFeatured: $isFeatured\n      limit: $limit\n      offset: $offset\n    ) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetMerchProductsDocument,
    "\n  query GetMerchProductById($id: ID!, $language: String) {\n    merchProductById(id: $id, language: $language) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetMerchProductByIdDocument,
    "\n  query GetMerchCategories($language: String) {\n    merchCategories(language: $language) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetMerchCategoriesDocument,
    "\n  query GetMerchCategoryById($id: ID!, $language: String) {\n    merchCategoryById(id: $id, language: $language) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetMerchCategoryByIdDocument,
    "\n  query GetNewsArticles(\n    $language: String\n    $status: String\n    $priority: String\n    $categoryId: ID\n    $limit: Int\n    $offset: Int\n  ) {\n    newsArticles(\n      language: $language\n      status: $status\n      priority: $priority\n      categoryId: $categoryId\n      limit: $limit\n      offset: $offset\n    ) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetNewsArticlesDocument,
    "\n  query GetNewsArticleById($id: ID!, $language: String) {\n    newsArticleById(id: $id, language: $language) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetNewsArticleByIdDocument,
    "\n  query GetNewsCategories($language: String) {\n    newsCategories(language: $language) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetNewsCategoriesDocument,
    "\n  query GetNewsCategoryById($id: ID!, $language: String) {\n    newsCategoryById(id: $id, language: $language) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetNewsCategoryByIdDocument,
    "\n  query GetTenants {\n    tenants {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetTenantsDocument,
    "\n  query GetTenantById($id: ID!) {\n    tenantById(id: $id) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetTenantByIdDocument,
    "\n  query GetTenantBySlug($slug: String!) {\n    tenantBySlug(slug: $slug) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetTenantBySlugDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      success\n      message\n      user {\n        id\n        email\n        firstName\n        lastName\n        isActive\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      success\n      message\n      user {\n        id\n        email\n        firstName\n        lastName\n        isActive\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation Register(\n    $email: String!\n    $password: String!\n    $firstName: String!\n    $lastName: String!\n    $tenantSlug: String!\n  ) {\n    register(\n      email: $email\n      password: $password\n      firstName: $firstName\n      lastName: $lastName\n      tenantSlug: $tenantSlug\n    ) {\n      success\n      message\n      user {\n        id\n        email\n        firstName\n        lastName\n        isActive\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Register(\n    $email: String!\n    $password: String!\n    $firstName: String!\n    $lastName: String!\n    $tenantSlug: String!\n  ) {\n    register(\n      email: $email\n      password: $password\n      firstName: $firstName\n      lastName: $lastName\n      tenantSlug: $tenantSlug\n    ) {\n      success\n      message\n      user {\n        id\n        email\n        firstName\n        lastName\n        isActive\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation Logout {\n    logout\n  }\n"): (typeof documents)["\n  mutation Logout {\n    logout\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateMerchProduct($input: CreateMerchProductInput!) {\n    createMerchProduct(input: $input) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateMerchProduct($input: CreateMerchProductInput!) {\n    createMerchProduct(input: $input) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateMerchProduct($id: ID!, $input: UpdateMerchProductInput!) {\n    updateMerchProduct(id: $id, input: $input) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateMerchProduct($id: ID!, $input: UpdateMerchProductInput!) {\n    updateMerchProduct(id: $id, input: $input) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteMerchProduct($id: ID!) {\n    deleteMerchProduct(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteMerchProduct($id: ID!) {\n    deleteMerchProduct(id: $id)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateMerchCategory($input: CreateMerchCategoryInput!) {\n    createMerchCategory(input: $input) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateMerchCategory($input: CreateMerchCategoryInput!) {\n    createMerchCategory(input: $input) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateMerchCategory($id: ID!, $input: UpdateMerchCategoryInput!) {\n    updateMerchCategory(id: $id, input: $input) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateMerchCategory($id: ID!, $input: UpdateMerchCategoryInput!) {\n    updateMerchCategory(id: $id, input: $input) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteMerchCategory($id: ID!) {\n    deleteMerchCategory(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteMerchCategory($id: ID!) {\n    deleteMerchCategory(id: $id)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreatePresignedUploadUrl($fileType: String!) {\n    createPresignedUploadUrl(fileType: $fileType) {\n      uploadUrl\n      fileUrl\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePresignedUploadUrl($fileType: String!) {\n    createPresignedUploadUrl(fileType: $fileType) {\n      uploadUrl\n      fileUrl\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateNewsArticle($input: CreateNewsArticleInput!) {\n    createNewsArticle(input: $input) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateNewsArticle($input: CreateNewsArticleInput!) {\n    createNewsArticle(input: $input) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateNewsArticle($id: ID!, $input: UpdateNewsArticleInput!) {\n    updateNewsArticle(id: $id, input: $input) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateNewsArticle($id: ID!, $input: UpdateNewsArticleInput!) {\n    updateNewsArticle(id: $id, input: $input) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteNewsArticle($id: ID!) {\n    deleteNewsArticle(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteNewsArticle($id: ID!) {\n    deleteNewsArticle(id: $id)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateNewsCategory($input: CreateNewsCategoryInput!) {\n    createNewsCategory(input: $input) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateNewsCategory($input: CreateNewsCategoryInput!) {\n    createNewsCategory(input: $input) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateNewsCategory($id: ID!, $input: UpdateNewsCategoryInput!) {\n    updateNewsCategory(id: $id, input: $input) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateNewsCategory($id: ID!, $input: UpdateNewsCategoryInput!) {\n    updateNewsCategory(id: $id, input: $input) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteNewsCategory($id: ID!) {\n    deleteNewsCategory(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteNewsCategory($id: ID!) {\n    deleteNewsCategory(id: $id)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateTenant($input: CreateTenantInput!) {\n    createTenant(input: $input) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateTenant($input: CreateTenantInput!) {\n    createTenant(input: $input) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateTenant($id: ID!, $input: UpdateTenantInput!) {\n    updateTenant(id: $id, input: $input) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateTenant($id: ID!, $input: UpdateTenantInput!) {\n    updateTenant(id: $id, input: $input) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteTenant($id: ID!) {\n    deleteTenant(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteTenant($id: ID!) {\n    deleteTenant(id: $id)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMe {\n    me {\n      id\n      email\n      firstName\n      lastName\n      isActive\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetMe {\n    me {\n      id\n      email\n      firstName\n      lastName\n      isActive\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMerchProducts(\n    $language: String\n    $status: String\n    $categoryId: ID\n    $isFeatured: Boolean\n    $limit: Int\n    $offset: Int\n  ) {\n    merchProducts(\n      language: $language\n      status: $status\n      categoryId: $categoryId\n      isFeatured: $isFeatured\n      limit: $limit\n      offset: $offset\n    ) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetMerchProducts(\n    $language: String\n    $status: String\n    $categoryId: ID\n    $isFeatured: Boolean\n    $limit: Int\n    $offset: Int\n  ) {\n    merchProducts(\n      language: $language\n      status: $status\n      categoryId: $categoryId\n      isFeatured: $isFeatured\n      limit: $limit\n      offset: $offset\n    ) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMerchProductById($id: ID!, $language: String) {\n    merchProductById(id: $id, language: $language) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetMerchProductById($id: ID!, $language: String) {\n    merchProductById(id: $id, language: $language) {\n      id\n      sku\n      name\n      description\n      shortDescription\n      price\n      compareAtPrice\n      costPrice\n      currency\n      inventory\n      trackInventory\n      allowBackorder\n      minStock\n      maxStock\n      weight\n      dimensions\n      featuredImage\n      images\n      tags\n      hasVariants\n      options\n      variants {\n        id\n        sku\n        barcode\n        title\n        optionValues\n        price\n        compareAtPrice\n        costPrice\n        inventory\n        weight\n        dimensions\n        image\n        position\n        isAvailable\n        createdAt\n        updatedAt\n      }\n      metaTitle\n      metaDescription\n      searchKeywords\n      status\n      isFeatured\n      isDigital\n      publishedAt\n      category {\n        id\n        name\n        slug\n        description\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMerchCategories($language: String) {\n    merchCategories(language: $language) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetMerchCategories($language: String) {\n    merchCategories(language: $language) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMerchCategoryById($id: ID!, $language: String) {\n    merchCategoryById(id: $id, language: $language) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetMerchCategoryById($id: ID!, $language: String) {\n    merchCategoryById(id: $id, language: $language) {\n      id\n      name\n      slug\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetNewsArticles(\n    $language: String\n    $status: String\n    $priority: String\n    $categoryId: ID\n    $limit: Int\n    $offset: Int\n  ) {\n    newsArticles(\n      language: $language\n      status: $status\n      priority: $priority\n      categoryId: $categoryId\n      limit: $limit\n      offset: $offset\n    ) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetNewsArticles(\n    $language: String\n    $status: String\n    $priority: String\n    $categoryId: ID\n    $limit: Int\n    $offset: Int\n  ) {\n    newsArticles(\n      language: $language\n      status: $status\n      priority: $priority\n      categoryId: $categoryId\n      limit: $limit\n      offset: $offset\n    ) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetNewsArticleById($id: ID!, $language: String) {\n    newsArticleById(id: $id, language: $language) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetNewsArticleById($id: ID!, $language: String) {\n    newsArticleById(id: $id, language: $language) {\n      id\n      slug\n      title\n      subtitle\n      excerpt\n      byline\n      blocks\n      featuredImage\n      socialImage\n      location\n      source\n      status\n      priority\n      isBreaking\n      isFeatured\n      metaTitle\n      metaDescription\n      keywords\n      publishedAt\n      scheduledAt\n      category {\n        id\n        name\n        slug\n        description\n        color\n        icon\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetNewsCategories($language: String) {\n    newsCategories(language: $language) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetNewsCategories($language: String) {\n    newsCategories(language: $language) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetNewsCategoryById($id: ID!, $language: String) {\n    newsCategoryById(id: $id, language: $language) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetNewsCategoryById($id: ID!, $language: String) {\n    newsCategoryById(id: $id, language: $language) {\n      id\n      name\n      slug\n      description\n      color\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTenants {\n    tenants {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetTenants {\n    tenants {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTenantById($id: ID!) {\n    tenantById(id: $id) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetTenantById($id: ID!) {\n    tenantById(id: $id) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTenantBySlug($slug: String!) {\n    tenantBySlug(slug: $slug) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetTenantBySlug($slug: String!) {\n    tenantBySlug(slug: $slug) {\n      id\n      name\n      slug\n      domain\n      isActive\n      status\n      plan\n      createdAt\n      updatedAt\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;